// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package de.empulse.elastictest.searchexample.model.builder;

import de.empulse.elastictest.searchexample.model.FoodTruck;
import de.empulse.elastictest.searchexample.model.LocationPoint;

public class FoodTruckBuilder extends FoodTruckBuilderBase<FoodTruckBuilder> {
	public static FoodTruckBuilder foodTruck() {
		return new FoodTruckBuilder();
	}

	public FoodTruckBuilder() {
		super(new FoodTruck());
	}

	public FoodTruck build() {
		return getInstance();
	}
}

class FoodTruckBuilderBase<GeneratorT extends FoodTruckBuilderBase<GeneratorT>> {
	private FoodTruck instance;

	protected FoodTruckBuilderBase(FoodTruck aInstance) {
		instance = aInstance;
	}

	protected FoodTruck getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withDescription(String aValue) {
		instance.setDescription(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withLocationPoint(LocationPoint aValue) {
		instance.setLocationPoint(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withId(String aValue) {
		instance.setId(aValue);

		return (GeneratorT) this;
	}
}
