// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package de.empulse.elastictest.searchexample.model.builder;

import de.empulse.elastictest.searchexample.model.LocationPoint;
import de.empulse.elastictest.searchexample.model.TimeRange;

public class LocationPointBuilder extends
		LocationPointBuilderBase<LocationPointBuilder> {
	public static LocationPointBuilder locationPoint() {
		return new LocationPointBuilder();
	}

	public LocationPointBuilder() {
		super(new LocationPoint());
	}

	public LocationPoint build() {
		return getInstance();
	}
}

class LocationPointBuilderBase<GeneratorT extends LocationPointBuilderBase<GeneratorT>> {
	private LocationPoint instance;

	protected LocationPointBuilderBase(LocationPoint aInstance) {
		instance = aInstance;
	}

	protected LocationPoint getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withLatitude(Double aValue) {
		instance.setLatitude(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withLongitude(Double aValue) {
		instance.setLongitude(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withAddress(String aValue) {
		instance.setAddress(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTimeRange(TimeRange aValue) {
		instance.setTimeRange(aValue);

		return (GeneratorT) this;
	}
}
