// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package de.empulse.elastictest.searchexample.model.builder;

import de.empulse.elastictest.searchexample.model.Location;
import de.empulse.elastictest.searchexample.model.TimeRange;
import org.elasticsearch.common.geo.GeoPoint;

public class LocationBuilder extends LocationBuilderBase<LocationBuilder> {
	public static LocationBuilder location() {
		return new LocationBuilder();
	}

	public LocationBuilder() {
		super(new Location());
	}

	public Location build() {
		return getInstance();
	}
}

class LocationBuilderBase<GeneratorT extends LocationBuilderBase<GeneratorT>> {
	private Location instance;

	protected LocationBuilderBase(Location aInstance) {
		instance = aInstance;
	}

	protected Location getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withAddress(String aValue) {
		instance.setAddress(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTimeRange(TimeRange aValue) {
		instance.setTimeRange(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPoint(GeoPoint aValue) {
		instance.setPoint(aValue);

		return (GeneratorT) this;
	}
}
