// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package de.empulse.elastictest.searchexample.model.builder;

import de.empulse.elastictest.searchexample.model.TimeRange;
import java.util.Date;

public class TimeRangeBuilder extends TimeRangeBuilderBase<TimeRangeBuilder> {
	public static TimeRangeBuilder timeRange() {
		return new TimeRangeBuilder();
	}

	public TimeRangeBuilder() {
		super(new TimeRange());
	}

	public TimeRange build() {
		return getInstance();
	}
}

class TimeRangeBuilderBase<GeneratorT extends TimeRangeBuilderBase<GeneratorT>> {
	private TimeRange instance;

	protected TimeRangeBuilderBase(TimeRange aInstance) {
		instance = aInstance;
	}

	protected TimeRange getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withFrom(Date aValue) {
		instance.setFrom(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTo(Date aValue) {
		instance.setTo(aValue);

		return (GeneratorT) this;
	}
}
